### PR TITLE
Added Configurable Stop command timeout values

### PR DESCRIPTION
**Pull request by kelvinschutz**
I ran into this recently with an app that needed to close down gracefully and not doing so in the allotted time. After finding a submitted issue to make these timeout values configurable, I went ahead and added them myself. You might have envisioned something else, but this seemed like the most straightforward approach from a first glance.

Just wanted to say thanks for putting the library together in the first place! I've already found it immensely useful myself :)

### CODE REVIEW

**Comment by lparkermg** [comment]
Would it be worth having the Start command timeout configurable as well as the Stop one?

**Comment by PeterKottas** [comment]
Looks good to me! And you are also right @kelvinschutz so far I am happy with start just waiting for the underlying implementation to fire.

**Comment by PeterKottas** [comment]
Also, would you be able to add this change to readme pls? I intentionally merged this right away cause I think you waited long enough (sry about that). But if you find some time, it would be great if you put a mention of this in the docs. Thanks!

**Comment by kelvinschutz** [comment]
Absolutely can do! Will update it the first chance I get.

**Comment by PeterKottas** [comment]
Thanks @kelvinschutz you're a ⭐️

**Pull request merged**
