### PR TITLE
Implemented OnCustomCommand

### LINKED ISSUE #122: Implement OnCustomCommand
ServiceRunner allows hooking into the various service events, e.g. OnStart, OnStop, etc... However, there is no method for OnCustomCommand so I can't port over to this nuget package.

```
ServiceRunner<ServiceApplication>.Run(config =>
			{
				var name = config.GetDefaultName();
				config.Service(serviceConfig =>
				{
					serviceConfig.ServiceFactory((extraArguments, microServiceController) =>
					{
						return new ServiceApplication();
					});
					serviceConfig.OnCustomCommand((service, int command) =>
					{
						Console.WriteLine("Service {0} custom command received: {1}", name, command);
					});
```

### PR DESCRIPTION
**Pull request by justintoth**
This fixes #122.

### CODE REVIEW

**Comment by PeterKottas** [comment]
I must admit I haven't got a chance (or time) to test this in detail. But I assume, since you put the work into it, that you had. That's why I'll just merge, release and hope for no issues ;)

**Comment by PeterKottas** [comment]
Thanks!

**Comment by justintoth** [comment]
@PeterKottas Cool, yes I did test it. Here is an example of how to call it:

`PS > dotnet ServiceName.dll action:custom-command command:200`

**Comment by PeterKottas** [comment]
Cool, I am not using this myself, but happy to have it here in case somebody needs to implement this behavior. Going over a few PRs. Need to fix some issues, once that's done, I'll release. Hopefully in like an hour.

**Comment by PeterKottas** [comment]
Ok 2.0.11 is out. Could you pls pull it down and just double check if everything works as expected? No rush

**Comment by justintoth** [comment]
Looks good. Thanks for releasing so quickly!

**Pull request merged**
